feat: make function of mock-generation, start to make markup template…
htmlacademy-ecmascript/1577653-big-trip-14 pull request #4
Opened 2021-04-08 12:10 UTC by olga-aheichyk

…s with mocks-data

2021-04-08 12:17 UTC, olga-aheichyk commented
Антон, привет. Это задание нескончаемое.
Отправляю пока что сделала.

Не могу придумать, как в форме редактирования поставить checked для типа точки и подходящих offers.

Ещё не совсем представляю, как сортировать моки по дате, из-за этого у меня все точки вперемешку в списке и дату поездки общую я пока не сделала.

2021-04-09 09:15 UTC, ademaro commented on src/main.js
> +const MOCKS = new Array(TRIP_EVENTS_COUNT).fill().map(generatePoint);
MOCKS => pointsData

2021-04-09 09:16 UTC, ademaro commented on src/mock/generate-point.js
> +const PHOTOS = [];
Константа, которую ты изменяешь?)

2021-04-09 09:17 UTC, ademaro commented on src/mock/generate-point.js
> +    src: getRandomElementFromArray(generatePhotosSrcArray()),
почему бы сразу тут не генерировать строку, вместо того, что бы генерировать массив строк и выбирать оттуда случайную строку?

2021-04-09 09:20 UTC, ademaro commented on src/mock/generate-point.js
> +    id: getRandomInteger(1, 20),
id могут дублироваться, давай сразу nanoid

2021-04-09 09:24 UTC, ademaro commented on src/view/trip-info-cost.js
> +    .map((array) => array.map((offer) => offer.price).reduce((sum, item) => sum + item, 0))
почитаемее бы сделать эту строку)

2021-04-09 09:26 UTC, ademaro requested changes
В целом всё очень хорошо, давай мелочи оправим и двинем дальше, завтра буду доступен для консультации, можем разобрать более детально

2021-04-12 14:42 UTC, ademaro commented
Обрати внимание, что идентификаторы в шаблоне не всегда соответствуют https://i.imgur.com/7JgggBH.png

2021-04-12 15:51 UTC, ademaro commented on src/main.js
> +const pointsData = new Array(TRIP_EVENTS_COUNT).fill().map(generatePoint);
Я бы сделал сразу generatePoints с параметром сколько надо генерить точек

2021-04-12 15:51 UTC, ademaro commented on src/main.js
> +const sortByDateAscending = (a, b) => new Date(a) - new Date(b);
В утилсы

2021-04-12 15:53 UTC, ademaro commented on src/mock/generate-point.js
> +const PHOTOS = [];
Надо поменять))

2021-04-12 15:54 UTC, ademaro commented on src/util.js
> +import dayjs from 'dayjs';
перемещаем файл в mocks/util.js, в корне — будут для проекта, а не для моков

2021-04-12 15:54 UTC, ademaro commented on src/view/trip-events-edit.js
> +const TYPES = ['Taxi', 'Bus', 'Train', 'Ship', 'Transport', 'Drive', 'Flight', 'Check-in', 'Sightseeing', 'Restaurant'];
Почему константы в шаблоне?

2021-04-12 15:55 UTC, ademaro commented on src/view/trip-events-edit.js
> +      <span class="event__offer-title">${item.name}</span>
по отступам хотелось бы видеть порядок)

2021-04-12 15:56 UTC, ademaro approved these changes
В целом всё хорошо, жду поправок тогда в следующем задании отдельным коммитом

2021-04-12 15:56 UTC, merged

2021-04-13 08:11 UTC, olga-aheichyk commented on src/mock/generate-point.js
> +const PHOTOS = [];
Здесь линтер ругается на let